name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Dovyski/setup-opencv-action@v1
    - uses: lukka/get-cmake@v3.18.0
      with:
        opencv-version: master
    - name: get-cmake
    - name: run CMake
      run: cmake .
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

