name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Dovyski/setup-opencv-action@v1
      with:
        opencv-version: master
    - name: run-cmake
      uses: lukka/run-cmake@v2.5
